// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1BiWG7uiTJRjLcMQhKsRS2m0CRQfc1Y',
    appId: '1:443131418714:web:967590075cfca39d44e063',
    messagingSenderId: '443131418714',
    projectId: 'media-boom-797f6',
    authDomain: 'media-boom-797f6.firebaseapp.com',
    storageBucket: 'media-boom-797f6.firebasestorage.app',
    measurementId: 'G-X8T3TE26J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvkVGvPk4ic4RNjy9WKQ2QgNbw4RZCb7M',
    appId: '1:443131418714:android:cf7c6388f4d1378c44e063',
    messagingSenderId: '443131418714',
    projectId: 'media-boom-797f6',
    storageBucket: 'media-boom-797f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwrDTISN7m-4Gl50YC9y7LQNQBCBaLyc',
    appId: '1:443131418714:ios:2532ca21727b518444e063',
    messagingSenderId: '443131418714',
    projectId: 'media-boom-797f6',
    storageBucket: 'media-boom-797f6.firebasestorage.app',
    iosClientId: '443131418714-2or2aoukivq8i4uov4f5ftjjfoj5sgr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaBoomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKwrDTISN7m-4Gl50YC9y7LQNQBCBaLyc',
    appId: '1:443131418714:ios:2532ca21727b518444e063',
    messagingSenderId: '443131418714',
    projectId: 'media-boom-797f6',
    storageBucket: 'media-boom-797f6.firebasestorage.app',
    iosClientId: '443131418714-2or2aoukivq8i4uov4f5ftjjfoj5sgr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaBoomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd1BiWG7uiTJRjLcMQhKsRS2m0CRQfc1Y',
    appId: '1:443131418714:web:28aa1a8520c58d5a44e063',
    messagingSenderId: '443131418714',
    projectId: 'media-boom-797f6',
    authDomain: 'media-boom-797f6.firebaseapp.com',
    storageBucket: 'media-boom-797f6.firebasestorage.app',
    measurementId: 'G-BZH47YDJSK',
  );
}
